# 🧠 Student Mental Health Prediction
## Data Understanding
### Author
Ahlam EL BOUJADI
### Project
End-to-End Machine Learning Project
### Description
ce notebook focuse sur la phase de data understanding de la methodologie  CRISP_DM 
l'objectif c'est de comprendre les données apres le pretraitement de machine learnnings
During this notebook, we will:
- Load the dataset
- Explore its structure
- Identify the variables
- Understand the data types
- Identify the target variable
- Produce an initial overview of the dataset

In [2]:
#importations des bibliotheques
import pandas as pd
import numpy as np

In [4]:
#importer la dataset
df = pd.read_csv("../dataset/student_depression_dataset.csv")

In [5]:
#affichage des 5 lignes du dataset
df.head()

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,'5-6 hours',Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,'5-6 hours',Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,'Less than 5 hours',Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,'7-8 hours',Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,'5-6 hours',Moderate,M.Tech,Yes,1.0,1.0,No,0

In [7]:
#savoir la dimension du dataset (nbre des lignes et nbres de colonnes)
print("nbre de lignes est ",df.shape[0])
print("nbre de colonnes est ",df.shape[1]   )

nbre de lignes est  27901
nbre de colonnes est  18

In [8]:
#savoir des informations  sur la dataset
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 27901 entries, 0 to 27900
Data columns (total 18 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   id                                     27901 non-null  int64
 1   Gender                                 27901 non-null  str
 2   Age                                    27901 non-null  float64
 3   City                                   27901 non-null  str
 4   Profession                             27901 non-null  str
 5   Academic Pressure                      27901 non-null  float64
 6   Work Pressure                          27901 non-null  float64
 7   CGPA                                   27901 non-null  float64
 8   Study Satisfaction                     27901 non-null  float64
 9   Job Satisfaction                       27901 non-null  float64
 10  Sleep Duration                         27901 non-null  str
 11  Dietary Habits                         27901 non-null  str
 12  Degree                                 27901 non-null  str
 13  Have you ever had suicidal thoughts ?  27901 non-null  str
 14  Work/Study Hours                       27901 non-null  float64
 15  Financial Stress                       27901 non-null  str
 16  Family History of Mental Illness       27901 non-null  str
 17  Depression                             27901 non-null  int64
dtypes: float64(7), int64(2), str(9)
memory usage: 5.3 MB

In [10]:
#affichage des noms des colonnes
df.columns

Index(['id', 'Gender', 'Age', 'City', 'Profession', 'Academic Pressure',
       'Work Pressure', 'CGPA', 'Study Satisfaction', 'Job Satisfaction',
       'Sleep Duration', 'Dietary Habits', 'Degree',
       'Have you ever had suicidal thoughts ?', 'Work/Study Hours',
       'Financial Stress', 'Family History of Mental Illness', 'Depression'],
      dtype='str')

In [11]:
#les types des données 
df.dtypes

id                                         int64
Gender                                       str
Age                                      float64
City                                         str
Profession                                   str
Academic Pressure                        float64
Work Pressure                            float64
CGPA                                     float64
Study Satisfaction                       float64
Job Satisfaction                         float64
Sleep Duration                               str
Dietary Habits                               str
Degree                                       str
Have you ever had suicidal thoughts ?        str
Work/Study Hours                         float64
Financial Stress                             str
Family History of Mental Illness             str
Depression                                 int64
dtype: object

In [15]:
#expression de la variable cible
target = "Depression"

print("Target Variable :", target)

Target Variable : Depression

In [17]:
#des statistiques sur la data
df.describe()

,id,Age,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Work/Study Hours,Depression
count,27901.000000,27901.000000,27901.000000,27901.000000,27901.000000,27901.000000,27901.000000,27901.000000,27901.000000
mean,70442.149421,25.822300,3.141214,0.000430,7.656104,2.943837,0.000681,7.156984,0.585499
std,40641.175216,4.905687,1.381465,0.043992,1.470707,1.361148,0.044394,3.707642,0.492645
min,2.000000,18.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,35039.000000,21.000000,2.000000,0.000000,6.290000,2.000000,0.000000,4.000000,0.000000
50%,70684.000000,25.000000,3.000000,0.000000,7.770000,3.000000,0.000000,8.000000,1.000000
75%,105818.000000,30.000000,4.000000,0.000000,8.920000,4.000000,0.000000,10.000000,1.000000
max,140699.000000,59.000000,5.000000,5.000000,10.000000,5.000000,4.000000,12.000000,1.000000

# 📝 Conclusion

Au cours de cette première phase de compréhension des données, nous avons exploré la structure générale du jeu de données **Student Depression Dataset**.

Les principales informations obtenues sont les suivantes :

- Le dataset a été chargé avec succès.
- Les dimensions du jeu de données ont été identifiées (nombre de lignes et de colonnes).
- Les différentes variables ont été recensées et leurs types ont été vérifiés.
- La variable cible **Depression** a été identifiée.
- Une première analyse descriptive des variables numériques a été réalisée.

Cette étape nous a permis d'acquérir une vision globale du dataset avant de commencer l'analyse exploratoire.

La prochaine étape consistera à réaliser une **Analyse Exploratoire des Données (EDA)** afin d'étudier la qualité des données, les distributions des variables, les relations entre celles-ci et leur influence sur la variable cible.