# Data Preparation

## Student Mental Health Prediction

### Objectif

Après avoir exploré et analysé le jeu de données lors de la phase d'EDA, cette étape consiste à préparer les données pour la phase de modélisation.

L'objectif est d'obtenir un jeu de données propre, cohérent et directement exploitable par les algorithmes de Machine Learning.
# Data Preparation

## Student Mental Health Prediction

### Objectif

Après avoir exploré et analysé le jeu de données lors de la phase d'Analyse Exploratoire des Données (EDA), cette étape consiste à préparer les données pour la phase de modélisation.

Le Data Preparation regroupe l'ensemble des opérations permettant de transformer un jeu de données brut en un jeu de données propre, cohérent et exploitable par les algorithmes de Machine Learning.

Les principales opérations réalisées dans cette phase seront :

- Suppression des variables non pertinentes ;
- Traitement des valeurs manquantes ;
- Vérification et conversion des types de données ;
- Encodage des variables catégorielles ;
- Normalisation des variables numériques (si nécessaire) ;
- Séparation des données d'entraînement et de test.

À l'issue de cette étape, le jeu de données sera prêt pour la construction et l'évaluation des modèles de Machine Learning.
Les principales opérations réalisées dans cette phase sont :

- Vérification des incohérences ;
- Traitement des valeurs manquantes ;
- Traitement des valeurs aberrantes ;
- Conversion des types de données ;
- Encodage des variables catégorielles ;
- Normalisation des variables numériques (si nécessaire) ;
- Séparation des données d'entraînement et de test.

#  Importation des bibliothèques

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Chargement du jeu de données

In [3]:

df = pd.read_csv("../dataset/raw/student_depression_dataset.csv")
df.head()

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,'5-6 hours',Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,'5-6 hours',Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,'Less than 5 hours',Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,'7-8 hours',Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,'5-6 hours',Moderate,M.Tech,Yes,1.0,1.0,No,0

# 1. Contrôle de cohérence du jeu de données

## Objectif

Avant d'appliquer des transformations, il est nécessaire de vérifier que le jeu de données est cohérent et correspond bien à celui utilisé lors de l'analyse exploratoire (EDA).

Cette étape permet de confirmer :

- le nombre d'observations ;
- le nombre de variables ;
- les types de données ;
- la présence éventuelle de valeurs manquantes ou d'incohérences.

Cette vérification garantit que toutes les étapes de prétraitement seront réalisées sur une base fiable.

In [4]:
df.shape

(27901, 18)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 27901 entries, 0 to 27900
Data columns (total 18 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   id                                     27901 non-null  int64
 1   Gender                                 27901 non-null  str
 2   Age                                    27901 non-null  float64
 3   City                                   27901 non-null  str
 4   Profession                             27901 non-null  str
 5   Academic Pressure                      27901 non-null  float64
 6   Work Pressure                          27901 non-null  float64
 7   CGPA                                   27901 non-null  float64
 8   Study Satisfaction                     27901 non-null  float64
 9   Job Satisfaction                       27901 non-null  float64
 10  Sleep Duration                         27901 non-null  str
 11  Dietary Habits                         27901 non-null  str
 12  Degree                                 27901 non-null  str
 13  Have you ever had suicidal thoughts ?  27901 non-null  str
 14  Work/Study Hours                       27901 non-null  float64
 15  Financial Stress                       27901 non-null  str
 16  Family History of Mental Illness       27901 non-null  str
 17  Depression                             27901 non-null  int64
dtypes: float64(7), int64(2), str(9)
memory usage: 5.3 MB

In [6]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
id,27901.0,70442.149421,40641.175216,2.0,35039.00,70684.00,105818.00,140699.0
Age,27901.0,25.822300,4.905687,18.0,21.00,25.00,30.00,59.0
Academic Pressure,27901.0,3.141214,1.381465,0.0,2.00,3.00,4.00,5.0
Work Pressure,27901.0,0.000430,0.043992,0.0,0.00,0.00,0.00,5.0
CGPA,27901.0,7.656104,1.470707,0.0,6.29,7.77,8.92,10.0
Study Satisfaction,27901.0,2.943837,1.361148,0.0,2.00,3.00,4.00,5.0
Job Satisfaction,27901.0,0.000681,0.044394,0.0,0.00,0.00,0.00,4.0
Work/Study Hours,27901.0,7.156984,3.707642,0.0,4.00,8.00,10.00,12.0
Depression,27901.0,0.585499,0.492645,0.0,0.00,1.00,1.00,1.0

In [7]:
df.describe(include="object").T

C:\Users\Hp\AppData\Local\Temp\ipykernel_22224\1274302342.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object").T

,count,unique,top,freq
Gender,27901,2,Male,15547
City,27901,52,Kalyan,1570
Profession,27901,14,Student,27870
Sleep Duration,27901,5,'Less than 5 hours',8310
Dietary Habits,27901,4,Unhealthy,10317
Degree,27901,28,'Class 12',6080
Have you ever had suicidal thoughts ?,27901,2,Yes,17656
Financial Stress,27901,6,5.0,6715
Family History of Mental Illness,27901,2,No,14398

# 2. Détection des incohérences

## Objectif

Avant de nettoyer les données, il est indispensable d'identifier les éventuelles incohérences présentes dans le jeu de données.

Une incohérence peut correspondre à :

- une erreur de saisie ;
- une valeur inattendue ;
- une modalité incorrecte ;
- une valeur manquante codée sous une autre forme.

L'identification de ces anomalies permet de choisir une stratégie de nettoyage adaptée et d'assurer la qualité du jeu de données avant la phase de modélisation.

In [8]:
categorical_columns = df.select_dtypes(include=['object']).columns
categorical_columns

C:\Users\Hp\AppData\Local\Temp\ipykernel_22224\2864691023.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(include=['object']).columns

Index(['Gender', 'City', 'Profession', 'Sleep Duration', 'Dietary Habits',
       'Degree', 'Have you ever had suicidal thoughts ?', 'Financial Stress',
       'Family History of Mental Illness'],
      dtype='str')

In [9]:
for col in categorical_columns:
    print(f"Variable : {col}")
    print(df[col].unique())
    print()

Variable : Gender
<ArrowStringArray>
['Male', 'Female']
Length: 2, dtype: str

Variable : City
<ArrowStringArray>
[       'Visakhapatnam',            'Bangalore',             'Srinagar',
             'Varanasi',               'Jaipur',                 'Pune',
                'Thane',              'Chennai',               'Nagpur',
               'Nashik',             'Vadodara',               'Kalyan',
               'Rajkot',            'Ahmedabad',              'Kolkata',
               'Mumbai',              'Lucknow',               'Indore',
                'Surat',             'Ludhiana',               'Bhopal',
               'Meerut',                 'Agra',            'Ghaziabad',
            'Hyderabad',          'Vasai-Virar',               'Kanpur',
                'Patna',            'Faridabad',                'Delhi',
               'Saanvi',               'M.Tech',               'Bhavna',
         ''Less Delhi'',                 'City',                  '3.0',
 ''Less than 5 Kalyan'',                 'Mira',               'Harsha',
               'Vaanya',               'Gaurav',                'Harsh',
              'Reyansh',               'Kibara',                'Rashi',
                   'ME',                'M.Com',               'Nalyan',
                'Mihir',               'Nalini',              'Nandini',
            'Khaziabad']
Length: 52, dtype: str

Variable : Profession
<ArrowStringArray>
[                 'Student',         ''Civil Engineer'',
                'Architect',         ''UX/UI Designer'',
       ''Digital Marketer'',         ''Content Writer'',
 ''Educational Consultant'',                  'Teacher',
                  'Manager',                     'Chef',
                   'Doctor',                   'Lawyer',
             'Entrepreneur',               'Pharmacist']
Length: 14, dtype: str

Variable : Sleep Duration
<ArrowStringArray>
[        ''5-6 hours'', ''Less than 5 hours'',         ''7-8 hours'',
 ''More than 8 hours'',              'Others']
Length: 5, dtype: str

Variable : Dietary Habits
<ArrowStringArray>
['Healthy', 'Moderate', 'Unhealthy', 'Others']
Length: 4, dtype: str

Variable : Degree
<ArrowStringArray>
[   'B.Pharm',        'BSc',         'BA',        'BCA',     'M.Tech',
        'PhD', ''Class 12'',       'B.Ed',        'LLB',         'BE',
       'M.Ed',        'MSc',        'BHM',    'M.Pharm',        'MCA',
         'MA',      'B.Com',         'MD',        'MBA',       'MBBS',
      'M.Com',     'B.Arch',        'LLM',     'B.Tech',        'BBA',
         'ME',        'MHM',     'Others']
Length: 28, dtype: str

Variable : Have you ever had suicidal thoughts ?
<ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str

Variable : Financial Stress
<ArrowStringArray>
['1.0', '2.0', '5.0', '3.0', '4.0', '?']
Length: 6, dtype: str

Variable : Family History of Mental Illness
<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str

## Incohérences détectées

Après inspection des variables catégorielles, plusieurs incohérences ont été identifiées.

| Variable | Incohérence observée | Décision |
|-----------|----------------------|----------|
| id | Identifiant unique | Suppression |
| City | Présence de prénoms, diplômes, textes et valeurs incohérentes | Suppression |
| Financial Stress | Présence du symbole `?` représentant une valeur manquante | Remplacement par `NaN` puis suppression des observations concernées |

# 3. Nettoyage des données

## Objectif

Après avoir identifié les différentes incohérences présentes dans le jeu de données, cette étape consiste à appliquer les transformations nécessaires afin d'obtenir un dataset propre et cohérent.

Les principales opérations réalisées sont :

- suppression des variables non pertinentes ;
- remplacement des valeurs incohérentes ;
- traitement des valeurs manquantes ;
- vérification de la qualité des données après nettoyage.

# Suppression des variables non pertinentes

## Objectif

Toutes les variables présentes dans un jeu de données ne contribuent pas nécessairement à la prédiction de la variable cible.

Avant de construire les modèles de Machine Learning, il est donc important d'identifier les variables qui n'apportent pas d'information pertinente ou qui risquent d'introduire du bruit dans les données.

Dans notre projet, deux variables ont été supprimées :

- **id** : identifiant unique de chaque étudiant, sans valeur prédictive.
- **City** : variable présentant une forte cardinalité, plusieurs valeurs incohérentes et n'ayant pas montré de contribution significative lors de l'analyse exploratoire.

In [10]:
print(df.columns)

Index(['id', 'Gender', 'Age', 'City', 'Profession', 'Academic Pressure',
       'Work Pressure', 'CGPA', 'Study Satisfaction', 'Job Satisfaction',
       'Sleep Duration', 'Dietary Habits', 'Degree',
       'Have you ever had suicidal thoughts ?', 'Work/Study Hours',
       'Financial Stress', 'Family History of Mental Illness', 'Depression'],
      dtype='str')

In [11]:
"id" in df.columns

True

In [12]:
# Suppression de la colonne id
df = df.drop(columns=["id"])

In [13]:
"City" in df.columns

True

In [14]:
df = df.drop(columns=["City"])

In [15]:
df.head()

,Gender,Age,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,Male,33.0,Student,5.0,0.0,8.97,2.0,0.0,'5-6 hours',Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,Female,24.0,Student,2.0,0.0,5.90,5.0,0.0,'5-6 hours',Moderate,BSc,No,3.0,2.0,Yes,0
2,Male,31.0,Student,3.0,0.0,7.03,5.0,0.0,'Less than 5 hours',Healthy,BA,No,9.0,1.0,Yes,0
3,Female,28.0,Student,3.0,0.0,5.59,2.0,0.0,'7-8 hours',Moderate,BCA,Yes,4.0,5.0,Yes,1
4,Female,25.0,Student,4.0,0.0,8.13,3.0,0.0,'5-6 hours',Moderate,M.Tech,Yes,1.0,1.0,No,0


 Traitement des valeurs manquantes

## Objectif

Les valeurs manquantes peuvent perturber les algorithmes de Machine Learning et conduire à des résultats moins fiables. Il est donc nécessaire de les identifier puis de choisir une stratégie de traitement adaptée.

Plusieurs approches existent, telles que la suppression des observations concernées ou l'imputation des valeurs manquantes (moyenne, médiane, mode ou méthodes avancées).

Dans notre jeu de données, seules **3 observations** présentent une valeur manquante dans la variable **Financial Stress**, soit environ **0,01 %** de l'ensemble des données.

Compte tenu de cette très faible proportion, nous avons choisi de supprimer ces observations afin de conserver un jeu de données cohérent sans introduire de valeurs artificielles.

In [16]:
df.isnull().sum()

Gender                                   0
Age                                      0
Profession                               0
Academic Pressure                        0
Work Pressure                            0
CGPA                                     0
Study Satisfaction                       0
Job Satisfaction                         0
Sleep Duration                           0
Dietary Habits                           0
Degree                                   0
Have you ever had suicidal thoughts ?    0
Work/Study Hours                         0
Financial Stress                         0
Family History of Mental Illness         0
Depression                               0
dtype: int64

In [17]:
df = df.dropna()

## Remplacer ? par NaN

In [50]:
df = df.replace("?", np.nan)

In [51]:
missing_data = pd.DataFrame({
    "Valeurs manquantes": df.isnull().sum(),
    "Pourcentage (%)": round(df.isnull().mean()*100,2)
})

missing_data[missing_data["Valeurs manquantes"] > 0]

                Valeurs manquantes  Pourcentage (%)
Sleep Duration               27880            99.94

### Traitement des valeurs manquantes

Après remplacement des symboles `?` par des valeurs `NaN`, seules **3 observations** présentent une valeur manquante dans la variable **Financial Stress**, soit **0,01 %** de l'ensemble du jeu de données.

Cette proportion étant extrêmement faible, nous avons choisi de supprimer ces observations.

Cette stratégie permet de conserver un jeu de données propre sans introduire de biais liés à une méthode d'imputation.

In [20]:
# Suppression des lignes contenant des valeurs manquantes

df = df.dropna()

# Vérification

df.isnull().sum()

Gender                                   0
Age                                      0
Profession                               0
Academic Pressure                        0
Work Pressure                            0
CGPA                                     0
Study Satisfaction                       0
Job Satisfaction                         0
Sleep Duration                           0
Dietary Habits                           0
Degree                                   0
Have you ever had suicidal thoughts ?    0
Work/Study Hours                         0
Financial Stress                         0
Family History of Mental Illness         0
Depression                               0
dtype: int64

In [21]:
df.shape

(27898, 16)

In [22]:
df["Financial Stress"].unique()

<ArrowStringArray>
['1.0', '2.0', '5.0', '3.0', '4.0']
Length: 5, dtype: str

###
 Traitement des valeurs manquantes

Après remplacement des symboles `?` par des valeurs `NaN`, seules **3 observations** présentent une valeur manquante dans la variable **Financial Stress**.

Ces observations représentent environ **0,01 %** du jeu de données.

Étant donné cette proportion extrêmement faible, nous avons choisi de supprimer ces lignes plutôt que d'utiliser une méthode d'imputation.

Cette stratégie permet de conserver un jeu de données propre sans introduire de valeurs artificielles susceptibles d'influencer le modèle.

In [23]:
missing_data = pd.DataFrame({

    "Valeurs manquantes": df.isnull().sum(),

    "Pourcentage (%)": round(df.isnull().mean()*100,2)

})

missing_data

                                       Valeurs manquantes  Pourcentage (%)
Gender                                                  0              0.0
Age                                                     0              0.0
Profession                                              0              0.0
Academic Pressure                                       0              0.0
Work Pressure                                           0              0.0
CGPA                                                    0              0.0
Study Satisfaction                                      0              0.0
Job Satisfaction                                        0              0.0
Sleep Duration                                          0              0.0
Dietary Habits                                          0              0.0
Degree                                                  0              0.0
Have you ever had suicidal thoughts ?                   0              0.0
Work/Study Hours                                        0              0.0
Financial Stress                                        0              0.0
Family History of Mental Illness                        0              0.0
Depression                                              0              0.0

### Vérification

Après suppression des observations concernées, le jeu de données ne contient plus aucune valeur manquante.

Le dataset est désormais complet et prêt pour les étapes suivantes du prétraitement.

# 3. Vérification et conversion des types de données

## Objectif

Les algorithmes de Machine Learning nécessitent des données correctement typées. Cette étape consiste à vérifier le type de chaque variable et à convertir les colonnes lorsque cela est nécessaire.

Les variables numériques doivent être représentées sous forme de nombres (`int` ou `float`), tandis que les variables catégorielles resteront sous forme de texte avant leur encodage.

In [24]:
df.info()

<class 'pandas.DataFrame'>
Index: 27898 entries, 0 to 27900
Data columns (total 16 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Gender                                 27898 non-null  str
 1   Age                                    27898 non-null  float64
 2   Profession                             27898 non-null  str
 3   Academic Pressure                      27898 non-null  float64
 4   Work Pressure                          27898 non-null  float64
 5   CGPA                                   27898 non-null  float64
 6   Study Satisfaction                     27898 non-null  float64
 7   Job Satisfaction                       27898 non-null  float64
 8   Sleep Duration                         27898 non-null  str
 9   Dietary Habits                         27898 non-null  str
 10  Degree                                 27898 non-null  str
 11  Have you ever had suicidal thoughts ?  27898 non-null  str
 12  Work/Study Hours                       27898 non-null  float64
 13  Financial Stress                       27898 non-null  str
 14  Family History of Mental Illness       27898 non-null  str
 15  Depression                             27898 non-null  int64
dtypes: float64(7), int64(1), str(8)
memory usage: 4.9 MB

In [25]:
#sparer les variables numeriques et catégorielle 
categorical_columns = df.select_dtypes(
    include=["object", "string"]
).columns.tolist()

numerical_columns = df.select_dtypes(
    include=["int64", "float64"]
).columns.tolist()

print("Variables catégorielles :")
print(categorical_columns)

print()

print("Variables numériques :")
print(numerical_columns)

Variables catégorielles :
['Gender', 'Profession', 'Sleep Duration', 'Dietary Habits', 'Degree', 'Have you ever had suicidal thoughts ?', 'Financial Stress', 'Family History of Mental Illness']

Variables numériques :
['Age', 'Academic Pressure', 'Work Pressure', 'CGPA', 'Study Satisfaction', 'Job Satisfaction', 'Work/Study Hours', 'Depression']

# 5. Encodage des variables catégorielles

## Objectif

Les algorithmes de Machine Learning ne peuvent pas traiter directement les variables textuelles. Il est donc nécessaire de convertir les variables catégorielles en valeurs numériques.

Le choix de la méthode d'encodage dépend de la nature de chaque variable. Dans ce projet, les variables binaires seront converties à l'aide d'un encodage simple, tandis que les autres variables catégorielles seront encodées de manière adaptée afin de préserver l'information contenue dans les données.

In [26]:
#voir les modalites exacte des tous les variables categorielles 
for col in categorical_columns:

    print(col)
    print(df[col].unique())
    print()

Gender
<ArrowStringArray>
['Male', 'Female']
Length: 2, dtype: str

Profession
<ArrowStringArray>
[                 'Student',         ''Civil Engineer'',
                'Architect',         ''UX/UI Designer'',
       ''Digital Marketer'',         ''Content Writer'',
 ''Educational Consultant'',                  'Teacher',
                  'Manager',                     'Chef',
                   'Doctor',                   'Lawyer',
             'Entrepreneur',               'Pharmacist']
Length: 14, dtype: str

Sleep Duration
<ArrowStringArray>
[        ''5-6 hours'', ''Less than 5 hours'',         ''7-8 hours'',
 ''More than 8 hours'',              'Others']
Length: 5, dtype: str

Dietary Habits
<ArrowStringArray>
['Healthy', 'Moderate', 'Unhealthy', 'Others']
Length: 4, dtype: str

Degree
<ArrowStringArray>
[   'B.Pharm',        'BSc',         'BA',        'BCA',     'M.Tech',
        'PhD', ''Class 12'',       'B.Ed',        'LLB',         'BE',
       'M.Ed',        'MSc',        'BHM',    'M.Pharm',        'MCA',
         'MA',      'B.Com',         'MD',        'MBA',       'MBBS',
      'M.Com',     'B.Arch',        'LLM',     'B.Tech',        'BBA',
         'ME',        'MHM',     'Others']
Length: 28, dtype: str

Have you ever had suicidal thoughts ?
<ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str

Financial Stress
<ArrowStringArray>
['1.0', '2.0', '5.0', '3.0', '4.0']
Length: 5, dtype: str

Family History of Mental Illness
<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str

In [27]:
df["Gender"] = df["Gender"].map({
    "Male": 0,
    "Female": 1
})

In [56]:
df["Have you ever had suicidal thoughts ?"] = \
df["Have you ever had suicidal thoughts ?"].map({
    "No":0,
    "Yes":1
})

In [29]:
df["Family History of Mental Illness"] = \
df["Family History of Mental Illness"].map({
    "No":0,
    "Yes":1
})

In [30]:
sleep_mapping = {
    "Less than 5 hours":0,
    "5-6 hours":1,
    "7-8 hours":2,
    "More than 8 hours":3,
    "Others":4
}

df["Sleep Duration"] = df["Sleep Duration"].map(sleep_mapping)

In [31]:
diet_mapping = {

    "Unhealthy":0,

    "Moderate":1,

    "Healthy":2,

    "Others":3

}

df["Dietary Habits"] = df["Dietary Habits"].map(diet_mapping)

In [32]:
le_profession = LabelEncoder()

df["Profession"] = le_profession.fit_transform(df["Profession"])

In [33]:
le_degree = LabelEncoder()

df["Degree"] = le_degree.fit_transform(df["Degree"])

# 6. Séparation des variables explicatives et de la variable cible

## Objectif

Avant d'entraîner un modèle de Machine Learning, il est nécessaire de séparer les variables explicatives (features) de la variable cible (target).

Les variables explicatives correspondent aux caractéristiques utilisées pour prédire le phénomène étudié.

La variable cible représente le résultat que le modèle doit apprendre à prédire.

Dans ce projet :

- Les variables explicatives sont regroupées dans **X**.
- La variable cible **Depression** est stockée dans **y**.

In [34]:
# Variables explicatives
X = df.drop(columns=["Depression"])

# Variable cible
y = df["Depression"]

In [35]:
print("Dimensions de X :", X.shape)
print("Dimensions de y :", y.shape)

Dimensions de X : (27898, 15)
Dimensions de y : (27898,)

In [36]:
X.head()

,Gender,Age,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness
0,0,33.0,12,5.0,0.0,8.97,2.0,0.0,NaN,2,4,1,3.0,1.0,0
1,1,24.0,12,2.0,0.0,5.90,5.0,0.0,NaN,1,11,0,3.0,2.0,1
2,0,31.0,12,3.0,0.0,7.03,5.0,0.0,NaN,2,6,0,9.0,1.0,1
3,1,28.0,12,3.0,0.0,5.59,2.0,0.0,NaN,1,8,1,4.0,5.0,1
4,1,25.0,12,4.0,0.0,8.13,3.0,0.0,NaN,1,17,1,1.0,1.0,0

In [37]:
y.head()

0    1
1    0
2    0
3    1
4    0
Name: Depression, dtype: int64

# 7. Séparation des données en ensembles d'entraînement et de test

## Objectif

Afin d'évaluer correctement les performances d'un modèle de Machine Learning, il est indispensable de séparer les données en deux ensembles :

- un ensemble d'entraînement (Training Set) utilisé pour apprendre les relations entre les variables ;
- un ensemble de test (Test Set) utilisé uniquement pour évaluer les performances du modèle sur de nouvelles observations.

Cette approche permet d'estimer la capacité de généralisation du modèle et de limiter le risque de surapprentissage (Overfitting).

In [38]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [39]:
print("X_train :", X_train.shape)
print("X_test :", X_test.shape)

print()

print("y_train :", y_train.shape)
print("y_test :", y_test.shape)

X_train : (22318, 15)
X_test : (5580, 15)

y_train : (22318,)
y_test : (5580,)

In [40]:
print("Répartition dans y :")
print(y.value_counts(normalize=True))

print()

print("Répartition dans y_train :")
print(y_train.value_counts(normalize=True))

print()

print("Répartition dans y_test :")
print(y_test.value_counts(normalize=True))

Répartition dans y :
Depression
1    0.585526
0    0.414474
Name: proportion, dtype: float64

Répartition dans y_train :
Depression
1    0.585536
0    0.414464
Name: proportion, dtype: float64

Répartition dans y_test :
Depression
1    0.585484
0    0.414516
Name: proportion, dtype: float64

# 8. Standardisation des variables numériques

## Objectif

Les variables numériques peuvent être exprimées sur des échelles très différentes.

La standardisation consiste à transformer ces variables afin qu'elles aient une moyenne proche de 0 et un écart-type proche de 1.

Cette étape est particulièrement importante pour les modèles sensibles à l'échelle des variables, tels que la Régression Logistique, les Support Vector Machines (SVM) et les algorithmes basés sur les distances comme KNN.

Afin d'éviter toute fuite d'information (Data Leakage), le StandardScaler est ajusté uniquement sur les données d'entraînement, puis appliqué aux données d'entraînement et de test.

In [41]:
numeric_features = [
    "Age",
    "Academic Pressure",
    "Work Pressure",
    "CGPA",
    "Study Satisfaction",
    "Job Satisfaction",
    "Work/Study Hours",
    "Financial Stress"
]

In [42]:
scaler = StandardScaler()
scaler

StandardScaler()

In [43]:
X_train[numeric_features] = scaler.fit_transform(
    X_train[numeric_features]
)

In [44]:
X_test[numeric_features] = scaler.transform(
    X_test[numeric_features]
)

In [45]:
X_train.head()

,Gender,Age,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness
21930,1,-1.598832,12,-0.103206,-0.008701,1.560863,1.507539,-0.01608,NaN,2,0,1,-1.396430,0.599648,1
4884,0,-1.395415,12,1.349100,-0.008701,-1.141086,-0.694231,-0.01608,NaN,2,0,1,0.764260,1.295662,1
26579,0,-0.378332,12,0.622947,-0.008701,-0.625136,0.773615,-0.01608,NaN,0,11,1,0.224088,1.295662,0
18970,1,0.435334,12,-0.103206,-0.008701,1.486186,0.773615,-0.01608,NaN,1,8,1,0.764260,1.295662,1
10437,0,-1.598832,12,-0.829360,-0.008701,1.173900,1.507539,-0.01608,NaN,2,0,1,1.304433,0.599648,0

# 9. Sauvegarde des données préparées

## Objectif

Après le prétraitement, les données sont enregistrées afin d'être réutilisées directement dans les prochaines étapes du projet, sans avoir à exécuter de nouveau toutes les opérations de nettoyage et de transformation.

In [46]:
import os

os.makedirs("../dataset/processed", exist_ok=True)

In [47]:
# Sauvegarde des ensembles d'entraînement et de test

X_train.to_csv("../dataset/processed/X_train.csv", index=False)
X_test.to_csv("../dataset/processed/X_test.csv", index=False)

y_train.to_csv("../dataset/processed/y_train.csv", index=False)
y_test.to_csv("../dataset/processed/y_test.csv", index=False)

# Conclusion

Au cours de cette phase de Data Preparation, le jeu de données a été nettoyé et transformé afin d'être exploitable par les algorithmes de Machine Learning.

Les principales opérations réalisées sont :

- suppression des variables non pertinentes ;
- traitement des incohérences et des valeurs manquantes ;
- encodage des variables catégorielles ;
- séparation des données en ensembles d'entraînement et de test ;
- standardisation des variables numériques.

Les données sont désormais prêtes pour la prochaine étape du projet : **Feature Engineering**, qui consistera à créer ou améliorer les variables afin d'optimiser les performances des futurs modèles de Machine Learning.

In [48]:
X_train.isnull().sum()

Gender                                       0
Age                                          0
Profession                                   0
Academic Pressure                            0
Work Pressure                                0
CGPA                                         0
Study Satisfaction                           0
Job Satisfaction                             0
Sleep Duration                           22306
Dietary Habits                               0
Degree                                       0
Have you ever had suicidal thoughts ?        0
Work/Study Hours                             0
Financial Stress                             0
Family History of Mental Illness             0
dtype: int64

In [52]:
print(df["Sleep Duration"].head(20))

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
6    NaN
7    NaN
8    NaN
9    NaN
10   NaN
11   NaN
12   NaN
13   NaN
14   NaN
15   NaN
16   NaN
17   NaN
18   NaN
19   NaN
Name: Sleep Duration, dtype: float64

In [53]:
X_train = X_train.dropna()

In [55]:
print(df["Sleep Duration"].head(20))

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
6    NaN
7    NaN
8    NaN
9    NaN
10   NaN
11   NaN
12   NaN
13   NaN
14   NaN
15   NaN
16   NaN
17   NaN
18   NaN
19   NaN
Name: Sleep Duration, dtype: float64